SEED_CATEGORIES = [
    {'slug': 'women', 'name': 'Thoi Trang Nu', 'description': 'San pham cho nu'},
    {'slug': 'men', 'name': 'Thoi Trang Nam', 'description': 'San pham cho nam'},
    {'slug': 'unisex', 'name': 'Thoi Trang Unisex', 'description': 'San pham unisex'},
    {'slug': 'ao-thun', 'name': 'Ao Thun', 'description': 'Ao thun co ban', 'parent_slug': 'unisex'},
    {'slug': 'ao-len', 'name': 'Ao Len', 'description': 'Ao len va cardigan', 'parent_slug': 'women'},
    {'slug': 'quan', 'name': 'Quan', 'description': 'Quan jean va quan tay', 'parent_slug': 'unisex'},
    {'slug': 'ao-khoac', 'name': 'Ao Khoac', 'description': 'Khoac ngoai', 'parent_slug': 'women'},
    {'slug': 'vay', 'name': 'Vay', 'description': 'Dam va vay', 'parent_slug': 'women'},
    {'slug': 'ao-so-mi', 'name': 'Ao So Mi', 'description': 'So mi casual va formal', 'parent_slug': 'men'},
    {'slug': 'giay', 'name': 'Giay', 'description': 'Sneaker va giay thoi trang', 'parent_slug': 'unisex'},
]

SEED_BRANDS = [
    {'name': 'Essence Basics', 'logo_url': '', 'description': 'Brand noi bo cho san pham co ban'},
    {'name': 'Essence Studio', 'logo_url': '', 'description': 'Dong san pham premium'},
]

SEED_PRODUCTS = [
    {
        'slug': 'ao-thun-trang-classic',
        'name': 'Ao Thun Trang Classic',
        'description': 'Ao thun thiet yeu vuot thoi gian duoc lam tu cotton cao cap.',
        'price': 299000,
        'sale_price': None,
        'stock_quantity': 120,
        'brand_name': 'Essence Basics',
        'category_slug': 'ao-thun',
        'average_rating': 4.8,
        'num_reviews': 342,
        'feature_text': 'cotton trang toi gian basic',
        'is_active': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1618677603544-51162346e165?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        'variants': [
            {'sku': 'TS-WHT-S', 'variant_attributes': {'color': 'Trang', 'size': 'S'}, 'price': None, 'stock_quantity': 20},
            {'sku': 'TS-WHT-M', 'variant_attributes': {'color': 'Trang', 'size': 'M'}, 'price': None, 'stock_quantity': 25},
            {'sku': 'TS-BLK-M', 'variant_attributes': {'color': 'Den', 'size': 'M'}, 'price': None, 'stock_quantity': 25},
            {'sku': 'TS-GRY-L', 'variant_attributes': {'color': 'Xam', 'size': 'L'}, 'price': None, 'stock_quantity': 18},
        ],
        'tags': ['best-seller', 'trending'],
    },
    {
        'slug': 'ao-len-cashmere',
        'name': 'Ao Len Cashmere',
        'description': 'Ao len cashmere mem mai sang trong voi thiet ke hien dai.',
        'price': 1299000,
        'sale_price': 899000,
        'stock_quantity': 60,
        'brand_name': 'Essence Studio',
        'category_slug': 'ao-len',
        'average_rating': 4.9,
        'num_reviews': 189,
        'feature_text': 'cashmere len am ap premium nu',
        'is_active': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1759873821397-433b7ea0eb7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        'variants': [
            {'sku': 'SW-BE-S', 'variant_attributes': {'color': 'Be', 'size': 'S'}, 'price': None, 'stock_quantity': 10},
            {'sku': 'SW-CREAM-M', 'variant_attributes': {'color': 'Kem', 'size': 'M'}, 'price': None, 'stock_quantity': 14},
            {'sku': 'SW-BLK-L', 'variant_attributes': {'color': 'Den', 'size': 'L'}, 'price': None, 'stock_quantity': 8},
        ],
        'tags': ['trending', 'sale'],
    },
    {
        'slug': 'quan-jean-den-slim-fit',
        'name': 'Quan Jean Den Slim Fit',
        'description': 'Vai denim cao cap co do co gian thoai mai.',
        'price': 799000,
        'sale_price': None,
        'stock_quantity': 100,
        'brand_name': 'Essence Basics',
        'category_slug': 'quan',
        'average_rating': 4.7,
        'num_reviews': 456,
        'feature_text': 'denim den slim fit jean',
        'is_active': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1744383390068-abfc7bc7fd07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        'variants': [
            {'sku': 'JE-BLK-30', 'variant_attributes': {'color': 'Den', 'size': '30'}, 'price': None, 'stock_quantity': 22},
            {'sku': 'JE-BLK-32', 'variant_attributes': {'color': 'Den', 'size': '32'}, 'price': None, 'stock_quantity': 24},
            {'sku': 'JE-BLU-34', 'variant_attributes': {'color': 'Xanh dam', 'size': '34'}, 'price': None, 'stock_quantity': 17},
        ],
        'tags': ['best-seller'],
    },
    {
        'slug': 'ao-khoac-da-len',
        'name': 'Ao Khoac Da Len',
        'description': 'Ao khoac len sang trong voi thiet ke co dien.',
        'price': 2499000,
        'sale_price': None,
        'stock_quantity': 40,
        'brand_name': 'Essence Studio',
        'category_slug': 'ao-khoac',
        'average_rating': 4.9,
        'num_reviews': 124,
        'feature_text': 'ao khoac da len classic cao cap',
        'is_active': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1763385230031-ea852e0858cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        'variants': [
            {'sku': 'CT-BE-M', 'variant_attributes': {'color': 'Be', 'size': 'M'}, 'price': None, 'stock_quantity': 8},
            {'sku': 'CT-BLK-L', 'variant_attributes': {'color': 'Den', 'size': 'L'}, 'price': None, 'stock_quantity': 6},
        ],
        'tags': ['new-arrival'],
    },
    {
        'slug': 'vay-midi-vai-lanh',
        'name': 'Vay Midi Vai Lanh',
        'description': 'Vay vai lanh thoang mat voi do dai midi thanh lich.',
        'price': 1199000,
        'sale_price': None,
        'stock_quantity': 55,
        'brand_name': 'Essence Studio',
        'category_slug': 'vay',
        'average_rating': 4.8,
        'num_reviews': 267,
        'feature_text': 'vay midi thoang mat thanh lich',
        'is_active': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1769107805528-964f4de0e342?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        'variants': [
            {'sku': 'DR-WHT-S', 'variant_attributes': {'color': 'Trang', 'size': 'S'}, 'price': None, 'stock_quantity': 12},
            {'sku': 'DR-SAND-M', 'variant_attributes': {'color': 'Cat', 'size': 'M'}, 'price': None, 'stock_quantity': 11},
        ],
        'tags': ['trending'],
    },
    {
        'slug': 'so-mi-oxford-cotton',
        'name': 'So Mi Oxford Cotton',
        'description': 'So mi cotton oxford co dien voi form dang vua van.',
        'price': 599000,
        'sale_price': None,
        'stock_quantity': 80,
        'brand_name': 'Essence Basics',
        'category_slug': 'ao-so-mi',
        'average_rating': 4.6,
        'num_reviews': 301,
        'feature_text': 'so mi oxford cotton nam',
        'is_active': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1722926628555-252c1c0258bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        'variants': [
            {'sku': 'SH-WHT-M', 'variant_attributes': {'color': 'Trang', 'size': 'M'}, 'price': None, 'stock_quantity': 20},
            {'sku': 'SH-BLU-L', 'variant_attributes': {'color': 'Xanh', 'size': 'L'}, 'price': None, 'stock_quantity': 16},
        ],
        'tags': ['best-seller'],
    },
]

SEED_INTERACTIONS = [
    {'user_id': None, 'session_id': 'guest-demo', 'product_slug': 'ao-thun-trang-classic', 'interaction_type': 'view', 'score': 1.0},
    {'user_id': None, 'session_id': 'guest-demo', 'product_slug': 'ao-len-cashmere', 'interaction_type': 'wishlist_add', 'score': 2.5},
    {'user_id': None, 'session_id': 'guest-demo', 'product_slug': 'quan-jean-den-slim-fit', 'interaction_type': 'add_to_cart', 'score': 3.0},
    {'user_id': None, 'session_id': 'guest-demo', 'product_slug': 'vay-midi-vai-lanh', 'interaction_type': 'purchase', 'score': 5.0},
]
